/*____ Core Header for STM32L073RZ 32 MHz, generated by NECTO ___*/

pub const ADDRESS_RCC_CRRCR : u32 = 0x40021008;
pub const VALUE_RCC_CRRCR   : u32 = 0x0;
pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
pub const VALUE_RCC_CR      : u32 = 0x1000001;
pub const ADDRESS_RCC_CFGR  : u32 = 0x4002100C;
pub const VALUE_RCC_CFGR    : u32 = 0x440003;
pub const ADDRESS_PWR_CR    : u32 = 0x40007000;
pub const VALUE_PWR_CR      : u32 = 0x1000;
pub const FOSC_KHZ_VALUE    : u32 = 32000;

/*____ Core Header for STM32L073RZ 4 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CRRCR : u32 = 0x40021008;
// pub const VALUE_RCC_CRRCR   : u32 = 0x0;
// pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
// pub const VALUE_RCC_CR      : u32 = 0x9;
// pub const ADDRESS_RCC_CFGR  : u32 = 0x4002100C;
// pub const VALUE_RCC_CFGR    : u32 = 0x440001;
// pub const ADDRESS_PWR_CR    : u32 = 0x40007000;
// pub const VALUE_PWR_CR      : u32 = 0x1000;
// pub const FOSC_KHZ_VALUE    : u32 = 4000;