on:
  push:
    branches: [ staging, trying, master ]
  pull_request:
  merge_group:

name: Code formatting check

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use the latest stable rustc
        run: rustup update stable && rustup default stable

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
