/*____ Core Header for STM32F411RE 100 MHz, generated by NECTO ___*/
 
pub const ADDRESS_RCC_CR      : u32 = 0x40023800;
pub const VALUE_RCC_CR        : u32 = 0x1000081;
pub const ADDRESS_RCC_PLLCFGR : u32 = 0x40023804;
pub const VALUE_RCC_PLLCFGR   : u32 = 0x4003210;
pub const ADDRESS_RCC_CFGR    : u32 = 0x40023808;
pub const VALUE_RCC_CFGR      : u32 = 0x1002;
pub const ADDRESS_SVRANGE     : u32 = 0x400FE070;
pub const VALUE_SVRANGE       : u32 = 0x3;
pub const FOSC_KHZ_VALUE      : u32 = 100000;

/*____ Core Header for STM32F411RE 16 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR      : u32 = 0x40023800;
// pub const VALUE_RCC_CR        : u32 = 0x81;
// pub const ADDRESS_RCC_PLLCFGR : u32 = 0x40023804;
// pub const VALUE_RCC_PLLCFGR   : u32 = 0x4003210;
// pub const ADDRESS_RCC_CFGR    : u32 = 0x40023808;
// pub const VALUE_RCC_CFGR      : u32 = 0x0;
// pub const ADDRESS_SVRANGE     : u32 = 0x400FE070;
// pub const VALUE_SVRANGE       : u32 = 0x3;
// pub const FOSC_KHZ_VALUE      : u32 = 16000;