/*____ * DOES NOT WORK * Core Header for STM32G070RB 64 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR         : u32 = 0x40021000;
// pub const VALUE_RCC_CR           : u32 = 0x1000100;
// pub const ADDRESS_RCC_CFGR       : u32 = 0x40021008;
// pub const VALUE_RCC_CFGR         : u32 = 0x2;
// pub const ADDRESS_RCC_PLLSYSCFGR : u32 = 0x4002100C;
// pub const VALUE_RCC_PLLSYSCFGR   : u32 = 0x303E0802;
// pub const ADDRESS_RCC_CCIPR      : u32 = 0x40021054;
// pub const VALUE_RCC_CCIPR        : u32 = 0x40000000;
// pub const ADDRESS_RCC_BDCR       : u32 = 0x4002105C;
// pub const VALUE_RCC_BDCR         : u32 = 0x0;
// pub const ADDRESS_RCC_CSR        : u32 = 0x40021060;
// pub const VALUE_RCC_CSR          : u32 = 0x0;
// pub const ADDRESS_PWR_CR1        : u32 = 0x40007000;
// pub const VALUE_PWR_CR1          : u32 = 0x400;
// pub const FOSC_KHZ_VALUE         : u32 = 64000;

/*____ Core Header for STM32G070RB 16 MHz, generated by NECTO ___*/

pub const ADDRESS_RCC_CR         : u32 = 0x40021000;
pub const VALUE_RCC_CR           : u32 = 0x00000081;
pub const ADDRESS_RCC_CFGR       : u32 = 0x40021008;
pub const VALUE_RCC_CFGR         : u32 = 0x0;
pub const ADDRESS_RCC_PLLSYSCFGR : u32 = 0x4002100C;
pub const VALUE_RCC_PLLSYSCFGR   : u32 = 0x0;
pub const ADDRESS_RCC_CCIPR      : u32 = 0x40021054;
pub const VALUE_RCC_CCIPR        : u32 = 0x0;
pub const ADDRESS_RCC_BDCR       : u32 = 0x4002105C;
pub const VALUE_RCC_BDCR         : u32 = 0x0;
pub const ADDRESS_RCC_CSR        : u32 = 0x40021060;
pub const VALUE_RCC_CSR          : u32 = 0x0;
pub const ADDRESS_PWR_CR1        : u32 = 0x40007000;
pub const VALUE_PWR_CR1          : u32 = 0x400;
pub const FOSC_KHZ_VALUE         : u32 = 32000;