/*____ Core Header for STM32L152RE 32 MHz, generated by NECTO ___*/

pub const ADDRESS_RCC_CR   : u32 = 0x40023800;
pub const VALUE_RCC_CR     : u32 = 0x61000001;
pub const ADDRESS_RCC_CFGR : u32 = 0x40023808;
pub const VALUE_RCC_CFGR   : u32 = 0x40440003;
pub const ADDRESS_SVCORE   : u32 = 0x40007000;
pub const VALUE_SVCORE     : u32 = 0x2;
pub const FOSC_KHZ_VALUE   : u32 = 32000;

/*____ Core Header for STM32L152RE 16 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR   : u32 = 0x40023800;
// pub const VALUE_RCC_CR     : u32 = 0x1;
// pub const ADDRESS_RCC_CFGR : u32 = 0x40023808;
// pub const VALUE_RCC_CFGR   : u32 = 0x2040001;
// pub const ADDRESS_SVCORE   : u32 = 0x40007000;
// pub const VALUE_SVCORE     : u32 = 0x2;
// pub const FOSC_KHZ_VALUE   : u32 = 16000;