/*____ Core Header for STM32F723ZE 216 MHz, generated by NECTO ___*/

pub const ADDRESS_RCC_CR      : u32 =  0x40023800;
pub const VALUE_RCC_CR        : u32 =  0x1000081;
pub const ADDRESS_RCC_PLLCFGR : u32 =  0x40023804;
pub const VALUE_RCC_PLLCFGR   : u32 =  0x9006C10;
pub const ADDRESS_RCC_CFGR    : u32 =  0x40023808;
pub const VALUE_RCC_CFGR      : u32 =  0x609402;
pub const ADDRESS_SVRANGE     : u32 =  0x400FE070;
pub const VALUE_SVRANGE       : u32 =  0x3;
pub const FOSC_KHZ_VALUE      : u32 =  216000;

/*____ Core Header for STM32F723ZE 16 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR      : u32 =  0x40023800;
// pub const VALUE_RCC_CR        : u32 =  0x81;
// pub const ADDRESS_RCC_PLLCFGR : u32 =  0x40023804;
// pub const VALUE_RCC_PLLCFGR   : u32 =  0x9006C10;
// pub const ADDRESS_RCC_CFGR    : u32 = 0x40023808;
// pub const VALUE_RCC_CFGR      : u32 = 0x600000;
// pub const ADDRESS_SVRANGE     : u32 = 0x400FE070;
// pub const VALUE_SVRANGE       : u32 = 0x3;
// pub const FOSC_KHZ_VALUE      : u32 = 16000;