/*____ Core Header for STM32F107VC 72 MHz, generated by NECTO ___*/
 
pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
pub const VALUE_RCC_CR      : u32 = 0x5010080;
pub const ADDRESS_RCC_CFGR  : u32 = 0x40021004;
pub const VALUE_RCC_CFGR    : u32 = 0x1D0402;
pub const ADDRESS_RCC_CFGR2 : u32 = 0x4002102C;
pub const VALUE_RCC_CFGR2   : u32 = 0x10644;
pub const FOSC_KHZ_VALUE    : u32 = 72000;  

/*____ Core Header for STM32F107VC 8 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
// pub const VALUE_RCC_CR      : u32 = 0x81;
// pub const ADDRESS_RCC_CFGR  : u32 = 0x40021004;
// pub const VALUE_RCC_CFGR    : u32 = 0x5C0000;
// pub const ADDRESS_RCC_CFGR2 : u32 = 0x4002102C;
// pub const VALUE_RCC_CFGR2   : u32 = 0x10000;
// pub const FOSC_KHZ_VALUE    : u32 = 8000;