/*____ Core Header for STM32F103RC 64 MHz, generated by NECTO ___*/
 
pub const ADDRESS_RCC_CR   : u32 = 0x40021000;
pub const VALUE_RCC_CR     : u32 = 0x1000081;
pub const ADDRESS_RCC_CFGR : u32 = 0x40021004;
pub const VALUE_RCC_CFGR   : u32 = 0x380402;
pub const FOSC_KHZ_VALUE   : u32 = 64000;  

/*____ Core Header for STM32F103RC 8 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR   : u32 = 0x40021000;
// pub const VALUE_RCC_CR     : u32 = 0x81;
// pub const ADDRESS_RCC_CFGR : u32 = 0x40021004;
// pub const VALUE_RCC_CFGR   : u32 = 0x380000;
// pub const FOSC_KHZ_VALUE   : u32 = 8000;