/*____ Core Header for STM32F042C6 48 MHz, generated by NECTO ___*/

pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
pub const VALUE_RCC_CR      : u32 = 0x1000081;
pub const ADDRESS_RCC_CFGR  : u32 = 0x40021004;
pub const VALUE_RCC_CFGR    : u32 = 0x8108002;
pub const ADDRESS_RCC_CFGR2 : u32 = 0x4002102C;
pub const VALUE_RCC_CFGR2   : u32 = 0x0;
pub const ADDRESS_RCC_CSR   : u32 = 0x40021024;
pub const VALUE_RCC_CSR     : u32 = 0x0;
pub const ADDRESS_RCC_CR2   : u32 = 0x40021034;
pub const VALUE_RCC_CR2     : u32 = 0x10080;
pub const FOSC_KHZ_VALUE    : u32 = 48000;

/*____ Core Header for STM32F042C6 8 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
// pub const VALUE_RCC_CR      : u32 = 0x81;
// pub const ADDRESS_RCC_CFGR  : u32 = 0x40021004;
// pub const VALUE_RCC_CFGR    : u32 = 0x80100000;
// pub const ADDRESS_RCC_CFGR2 : u32 = 0x4002102C;
// pub const VALUE_RCC_CFGR2   : u32 = 0x0;
// pub const ADDRESS_RCC_CSR   : u32 = 0x40021024;
// pub const VALUE_RCC_CSR     : u32 = 0x0;
// pub const ADDRESS_RCC_CR2   : u32 = 0x40021034;
// pub const VALUE_RCC_CR2     : u32 = 0x84;
// pub const FOSC_KHZ_VALUE    : u32 = 8000;