/*____ Core Header for STM32L432KC 80 MHz, generated by NECTO ___*/

pub const ADDRESS_RCC_CR      : u32 = 0x40021000;
pub const VALUE_RCC_CR        : u32 = 0x1000960;
pub const ADDRESS_RCC_CFGR    : u32 = 0x40021008;
pub const VALUE_RCC_CFGR      : u32 = 0x3;
pub const ADDRESS_RCC_PLLCFGR : u32 = 0x4002100C;
pub const VALUE_RCC_PLLCFGR   : u32 = 0x1000A02;
pub const ADDRESS_RCC_CSR     : u32 = 0x40021094;
pub const VALUE_RCC_CSR       : u32 = 0x600;
pub const ADDRESS_PWR_CR1     : u32 = 0x40007000;
pub const VALUE_PWR_CR1       : u32 = 0x200;
pub const ADDRESS_RCC_CRRCR   : u32 = 0x40021098;
pub const VALUE_RCC_CRRCR     : u32 = 0x0;
pub const ADDRESS_RCC_CCIPR   : u32 = 0x40021088;
pub const VALUE_RCC_CCIPR     : u32 = 0x0;
pub const FOSC_KHZ_VALUE      : u32 = 80000;

/*____ Core Header for STM32L432KC 16 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR      : u32 = 0x40021000;
// pub const VALUE_RCC_CR        : u32 = 0x960;
// pub const ADDRESS_RCC_CFGR    : u32 = 0x40021008;
// pub const VALUE_RCC_CFGR      : u32 = 0x8001;
// pub const ADDRESS_RCC_PLLCFGR : u32 = 0x4002100C;
// pub const VALUE_RCC_PLLCFGR   : u32 = 0x1000A00;
// pub const ADDRESS_RCC_CSR     : u32 = 0x40021094;
// pub const VALUE_RCC_CSR       : u32 = 0x600;
// pub const ADDRESS_PWR_CR1     : u32 = 0x40007000;
// pub const VALUE_PWR_CR1       : u32 = 0x200;
// pub const ADDRESS_RCC_CRRCR   : u32 = 0x40021098;
// pub const VALUE_RCC_CRRCR     : u32 = 0x0;
// pub const ADDRESS_RCC_CCIPR   : u32 = 0x40021088;
// pub const VALUE_RCC_CCIPR     : u32 = 0x0;
// pub const FOSC_KHZ_VALUE      : u32 = 16000;