/*____ Core Header for STM32F373VC 64 MHz, generated by NECTO ___*/

pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
pub const VALUE_RCC_CR      : u32 = 0x1000001;
pub const ADDRESS_RCC_CFGR  : u32 = 0x40021004;
pub const VALUE_RCC_CFGR    : u32 = 0x380402;
pub const ADDRESS_RCC_CFGR2 : u32 = 0x4002102C;
pub const VALUE_RCC_CFGR2   : u32 = 0x0;
pub const FOSC_KHZ_VALUE    : u32 = 64000;

/*____ Core Header for STM32F373VC 8 MHz, generated by NECTO ___*/

// pub const ADDRESS_RCC_CR    : u32 = 0x40021000;
// pub const VALUE_RCC_CR      : u32 = 0x1;
// pub const ADDRESS_RCC_CFGR  : u32 = 0x40021004;
// pub const VALUE_RCC_CFGR    : u32 = 0x380000;
// pub const ADDRESS_RCC_CFGR2 : u32 = 0x4002102C;
// pub const VALUE_RCC_CFGR2   : u32 = 0x0;
// pub const FOSC_KHZ_VALUE    : u32 = 8000;